Login, sign up, reset password CSS
rikyfocil/BerryCloud pull request #11
Opened 2016-10-20 22:10 UTC by rdorame

CSS to Login, Password reset, Sign up

2016-10-24 15:07 UTC, rikyfocil-old requested changes

2016-10-24 15:07 UTC, rikyfocil commented on public/css/style.css
> +    background: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('../img/action.jpeg');
Where does ../img/action.jpeg suppose to be?

2016-10-24 15:07 UTC, rikyfocil commented on public/css/style.css
> +    background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('../img/sun.jpeg') 50% 30%;
Same as above

2016-10-24 15:07 UTC, rikyfocil commented on resources/views/auth/login.blade.php
> +    <form id="login-form" class="text-left" role="form" method="POST" action="{{ url('/login') }}">
Its better to use route()

2016-10-24 15:07 UTC, rikyfocil commented on resources/views/auth/register.blade.php
> +      <p><a href="#">Already have an account?</a></p>
Change url to login

2016-10-24 22:41 UTC, Raul-MA submitted a review, later dismissed

2016-10-24 22:41 UTC, Raul-MA commented on resources/views/auth/register.blade.php
> +          <label for="reg_agree">I agree with <a href="#">terms & conditions</a></label>
Unsupported. Please change controller or remove checkbox.

2016-10-25 00:20 UTC, rdorame reviewed
Done

2016-10-25 00:26 UTC, rikyfocil-old requested changes

2016-10-25 00:26 UTC, rikyfocil commented on resources/views/auth/passwords/email.blade.php
> +  		<form class="text-left" role="form" method="POST" action="{{ url('/password/email') }}">
action with route please

2016-10-25 00:30 UTC, rikyfocil-old approved these changes

2016-10-25 00:31 UTC, merged