Asher dl
rikyfocil/BerryCloud pull request #21
Opened 2016-11-21 13:32 UTC by AsherDLL

Adding a dashboard for permission changes in the users. It can be accessed through http://.../permission 

TBC: Make that only root and administrative users can access to this dashboard.
TBD: Add a button to ban a user.

Adding new files in documentation/database folder, which include diagrams of
Laravel structure. Diagrams will be joined as a single file in a further
commit.

2016-11-21 16:59 UTC, rikyfocil requested changes
Also to the review:

Please add the validation for only allowing root users to change this

Please remove all diagrams as we may not include files that we don´t own. (And they are in the wrong folder)

There is no way to arrive to this view. Please add one, only for root users.

Also please remove virtual users from the list

2016-11-21 16:59 UTC, rikyfocil commented on app/User.php
> +        return $this->hasOne('App\UserType', 'id', 'idUserType');
Should be belongs according to Laravel standards.

 UserType may be a better name but you can leave it as permission

2016-11-21 16:59 UTC, rikyfocil commented on app/User.php
> +}
Add blank line at end of file

2016-11-21 16:59 UTC, rikyfocil commented on resources/views/permissions.blade.php
> +	<table class="table">
Make table like the rest of them. You can base on the files one

2016-11-21 16:59 UTC, rikyfocil commented on resources/views/permissions.blade.php
> +				{{ Form::open(array('url' => 'permission/' . $user->id)) }}
Use route and pass user->id as param

2016-11-21 16:59 UTC, rikyfocil commented on resources/views/permissions.blade.php
> +						<option {{ $user->permission->id == 1? "selected" :""}} value="1">Standard</option>
Should not be hardcoded. You may pass the user types available from the controllers

2016-11-21 16:59 UTC, rikyfocil commented on resources/views/permissions.blade.php
> +@endsection
End of line here

2016-11-21 16:59 UTC, rikyfocil commented on routes/web.php
> +use Illuminate\Http\Request;
Remove this as we are moving all logic to controllers

2016-11-21 16:59 UTC, rikyfocil commented on routes/web.php
> +Route::get('permission',function () {
Move to a controller

2016-11-21 16:59 UTC, rikyfocil commented on resources/views/permissions.blade.php
> +
Move the file to a folder to keep things organized

2016-11-21 16:59 UTC, rikyfocil commented on routes/web.php
> +	$change_permission = App\User::find($id);
Should validate for null or use firstOrFail()

2016-11-21 16:59 UTC, rikyfocil commented on routes/web.php
> +	$change_permission->idUserType = $request["permission"];
Should validate permission to be present and valid

2016-11-21 16:59 UTC, rikyfocil commented on routes/web.php
> +	return Redirect::to("permission");
we use return redirect()->route("name") in the rest of controllers. Can you change it to be consistent?

2016-11-23 02:09 UTC, AsherDLL commented on app/User.php
> +}
Fixed

2016-11-23 02:22 UTC, AsherDLL commented on resources/views/permissions.blade.php
> +
Do you want me to create a new folder named "permissions"? or where do you want me to move the file?

2016-11-23 02:44 UTC, AsherDLL commented on resources/views/permissions.blade.php
> +@endsection
Fixed

2016-11-23 19:39 UTC, AsherDLL commented on resources/views/permissions.blade.php
> +
Fixed

2016-11-23 19:45 UTC, AsherDLL commented on resources/views/permissions.blade.php
> +	<table class="table">
Fixed

2016-11-23 20:02 UTC, AsherDLL commented on routes/web.php
> +use Illuminate\Http\Request;
Fixed

2016-11-23 20:13 UTC, AsherDLL commented on routes/web.php
> +Route::get('permission',function () {
Fixed

2016-11-23 20:23 UTC, AsherDLL commented on routes/web.php
> +	$change_permission = App\User::find($id);
Fixed

2016-11-23 20:29 UTC, AsherDLL commented on routes/web.php
> +	$change_permission->idUserType = $request["permission"];
Fixed

2016-11-23 20:32 UTC, AsherDLL commented on routes/web.php
> +	return Redirect::to("permission");
Fixed

2016-11-23 20:41 UTC, AsherDLL commented on app/User.php
> +        return $this->hasOne('App\UserType', 'id', 'idUserType');
Won't fix

2016-11-25 19:08 UTC, AsherDLL commented on resources/views/permissions.blade.php
> +				{{ Form::open(array('url' => 'permission/' . $user->id)) }}
Fixed

2016-11-25 19:08 UTC, AsherDLL commented on resources/views/permissions.blade.php
> +						<option {{ $user->permission->id == 1? "selected" :""}} value="1">Standard</option>
Fixed

2016-11-25 19:30 UTC, AsherDLL commented on resources/views/permissions.blade.php
> +				{{ Form::open(array('url' => 'permission/' . $user->id)) }}
Won't Fix

2016-11-25 19:56 UTC, closed without merging