Asher dl
rikyfocil/BerryCloud pull request #24
Opened 2016-11-25 20:03 UTC by AsherDLL

**Pull request fixed**

Please add the correspondig button to land in my view from the main page(for root users only)

2016-11-26 19:05 UTC, rikyfocil-old commented on app/Http/Controllers/PermissionsController.php
> +		if(!Auth::check())
Next time place something like this

```
function __construct(){
    $this->middleware('auth');
}
```

With it only authenticated users can acces the route and non authenticated users will go to login.

2016-11-26 19:07 UTC, rikyfocil-old commented on app/Http/Controllers/PermissionsController.php
> +			return redirect()->route('home');
Can you change this for 
`abort(403);`
?

2016-11-26 19:07 UTC, rikyfocil-old commented on app/Http/Controllers/PermissionsController.php
> +			return redirect()->route('home');
Same as above

2016-11-26 19:08 UTC, rikyfocil-old commented on app/Http/Controllers/PermissionsController.php
> +		$change_permission->idUserType = $request["permission"];
Please validate the request
https://laravel.com/docs/5.3/validation

2016-11-26 19:10 UTC, rikyfocil-old requested changes

2016-11-26 19:10 UTC, rikyfocil-old commented on app/User.php
> +        return $this->hasOne('App\UserType', 'id', 'idUserType');
Still need to be changed for belongs

2016-11-27 01:35 UTC, AsherDLL commented on app/Http/Controllers/PermissionsController.php
> +		if(!Auth::check())
Ok

2016-11-27 01:37 UTC, AsherDLL commented on app/User.php
> +        return $this->hasOne('App\UserType', 'id', 'idUserType');
Fixed

2016-11-27 01:43 UTC, AsherDLL commented on app/Http/Controllers/PermissionsController.php
> +			return redirect()->route('home');
Fixed

2016-11-27 01:43 UTC, AsherDLL commented on app/Http/Controllers/PermissionsController.php
> +			return redirect()->route('home');
Fixed

2016-11-27 04:22 UTC, AsherDLL commented on app/Http/Controllers/PermissionsController.php
> +		$change_permission->idUserType = $request["permission"];
Fixed

2016-11-27 04:22 UTC, closed without merging